name: CI - ASP.NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:16
        env:
          POSTGRESQL_USERNAME: AspNetUSER
          POSTGRESQL_PASSWORD: AspNetPASS
          POSTGRESQL_DATABASE: PostgreSqlDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRESQL_USERNAME -h localhost -p 5432"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        dotnet-version: [9.0.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore "AspNetApi.csproj"

      - name: Build
        run: dotnet build "AspNetApi.csproj" --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
